# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static
platform :ios, '14.0'
prepare_react_native_project!

# Firebase requires modular headers
use_modular_headers!

# Firebase 10.x configuration - stable version

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# Temporarily disable Flipper to avoid boost issues
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DimaniWeekends' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DimaniWeekendsTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix for gRPC compilation issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['WARN_ABOUT_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        
        # Specific fixes for gRPC targets
        if ['gRPC-C++', 'gRPC-Core', 'BoringSSL-GRPC'].include?(target.name)
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_UNUSED_FUNCTIONS'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_UNUSED_VARIABLES'] = 'NO'
          
          # Remove problematic flags
          flags = config.build_settings['OTHER_CFLAGS'] || ''
          flags = flags.split.reject { |f| f.start_with?('-G') || f.start_with?('-W') }.join(' ')
          config.build_settings['OTHER_CFLAGS'] = flags
          
          # Add specific flags for gRPC
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=c++17'
        end
        
                          # Fix for Firebase 10.x compatibility
         if target.name.include?('Firebase')
           config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
           config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
         end
         
         # Fix for gRPC and BoringSSL
         if ['gRPC-C++', 'gRPC-Core', 'BoringSSL-GRPC', 'abseil'].include?(target.name)
           config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
           config.build_settings['DEFINES_MODULE'] = 'NO'
           config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'NO'
         end
        
        # Fix for React Native
        if target.name.include?('React')
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        end
      end
    end
  end
end
